### horizontal and vertical stacking


In [2]:
import numpy as np

In [3]:
matrix1 = np.random.randint(1,20,9).reshape(3,3)

In [4]:
matrix2 = np.random.randint(1,25,9).reshape(3,3)

In [5]:
matrix1

array([[15,  2, 12],
       [10, 13, 17],
       [ 9, 14,  7]])

In [6]:
matrix2

array([[ 5,  3,  7],
       [ 4, 22, 21],
       [ 7,  2,  6]])

In [8]:
#horizonatal stacking
np.hstack((matrix1,matrix2))

array([[15,  2, 12,  5,  3,  7],
       [10, 13, 17,  4, 22, 21],
       [ 9, 14,  7,  7,  2,  6]])

In [9]:
#vertical stacking
np.vstack((matrix1,matrix2))

array([[15,  2, 12],
       [10, 13, 17],
       [ 9, 14,  7],
       [ 5,  3,  7],
       [ 4, 22, 21],
       [ 7,  2,  6]])

In [10]:
#note :- if we perform vertical stacking on 1D array then it becomes a 2D array

## Numpy finishing Exercise

In [11]:
import numpy as np

In [12]:
arr = [1,3,6,7,3,8,9]

In [14]:
arr = np.array(arr)
arr

array([1, 3, 6, 7, 3, 8, 9])

In [16]:
np.arange(20,31)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [18]:
#array of 10 elements considtng only of 5
arr2 = np.random.randint(5,6,10)
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [42]:
#using ones method 
arr2 = np.ones(10) * 5
arr2 = arr2.astype(int)  #converting into int, can (divide) //1 also 
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [43]:
#1D to 3D
arr3 = np.array([1,2,34,5,6,5,6,8,8])
arr3 = arr3.reshape(3,3,-1)
arr3

array([[[ 1],
        [ 2],
        [34]],

       [[ 5],
        [ 6],
        [ 5]],

       [[ 6],
        [ 8],
        [ 8]]])

In [44]:
#array with 20 random int and repalce even no with -1 using broadcasting
arr4 = np.random.randint(20,50,20)
arr4

array([37, 32, 28, 49, 28, 49, 44, 39, 37, 32, 46, 23, 21, 37, 26, 35, 40,
       36, 44, 45])

In [45]:
condi = (arr4%2==0)
arr4[condi] = -1
arr4

array([37, -1, -1, 49, -1, 49, -1, 39, 37, -1, -1, 23, 21, 37, -1, 35, -1,
       -1, -1, 45])

In [46]:
#extracting a mini matrix out of a large matrix
arr = np.random.randint(20,80,30).reshape(6,-1)
arr

array([[74, 20, 27, 21, 45],
       [39, 62, 27, 37, 47],
       [37, 41, 39, 74, 45],
       [62, 30, 44, 41, 45],
       [53, 70, 65, 70, 71],
       [38, 47, 57, 69, 70]])

In [47]:
arr[2:5,1:]

array([[41, 39, 74, 45],
       [30, 44, 41, 45],
       [70, 65, 70, 71]])