### operation on multiple array 

In [2]:
import numpy as np

In [3]:
arr1 = np.array([2,5,15,18])

In [6]:
arr2 = np.array([6,8,3,8,])

In [8]:
arr1+arr2
#shape needs to be same

array([ 8, 13, 18, 26])

In [9]:
arr1*arr2

array([ 12,  40,  45, 144])

In [10]:
arr1.dot(arr2)

241

## more functions on array in numpy

In [11]:
np.min(arr1)

2

In [12]:
np.max(arr1)

18

In [13]:
np.argmin(arr2)

2

In [14]:
np.argmax(arr2)

1

In [15]:
np.sqrt(arr1)

array([1.41421356, 2.23606798, 3.87298335, 4.24264069])

In [17]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [21]:
arr3 = np.array([1,1,0,0,1],dtype=bool)
arr3

array([ True,  True, False, False,  True])