In [11]:
#using arr[], [] box to pass conditional statements   

In [12]:
import numpy as np

In [13]:
arr = np.arange(4,25)
arr


array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [14]:
arr>7

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [15]:
checkb = arr>7

In [16]:
arr[checkb]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr[arr<=13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [18]:
arr[arr%4==0]

array([ 4,  8, 12, 16, 20, 24])

In [19]:
arr[arr==9]

array([9])

In [20]:
arr[arr*6==30]

array([5])