#### view vs copy


In [1]:
import numpy as np

In [7]:
np.random.seed(34)
arr = np.random.choice(np.arange(1,50), size=13, replace=False)
arr

array([25, 18,  2,  4,  8, 28, 13,  1,  7, 10, 41, 47, 39])

In [9]:
arr_sample = arr[4:9]
arr

array([25, 18,  2,  4,  8, 28, 13,  1,  7, 10, 41, 47, 39])

In [10]:
#changing the samole array to see the view
arr_sample[:] = 0
arr_sample

array([0, 0, 0, 0, 0])

In [11]:
#arr will also have zero at the place ofthe view
arr

array([25, 18,  2,  4,  0,  0,  0,  0,  0, 10, 41, 47, 39])

In [32]:
####################creating copy instead ####################
np.random.seed(69)
new_arr = np.random.choice(np.arange(40,60),size=9,replace=False)
new_arr

array([54, 56, 57, 47, 42, 53, 52, 43, 50])

In [33]:
new_arr_sample = new_arr[3:7].copy()
new_arr_sample

array([47, 42, 53, 52])

In [34]:
new_arr_sample[:]=0
new_arr_sample

array([0, 0, 0, 0])

In [35]:
new_arr

array([54, 56, 57, 47, 42, 53, 52, 43, 50])