# Here we will practice together
## Data Visual Day1 basics 

In [3]:
3+4

7

#### del with dd, new cell with b, ctrl + enter, shift + enter

In [3]:
import numpy as np

In [4]:
nums = [1,2,3,4]
nums = np.array(nums)

In [5]:
print(nums)

[1 2 3 4]


### creating 2d and 3d array using numpy and some common fuctions

In [6]:
nums2 = np.array([[1,2,3],[4,5,6]])
print(nums2)

[[1 2 3]
 [4 5 6]]


In [13]:
print(nums.ndim)
nums2.ndim

1


2

In [13]:
print(nums.ndim)
nums2.ndim

1


2

In [13]:
print(nums.ndim)
nums2.ndim

1


2

In [22]:
nums3 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
nums3 = np.array(nums3)
print((nums3))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
print(nums3.ndim)

3


In [18]:
print(nums3.shape)
nums3.dtype

(2, 2, 3)


dtype('int32')

##### creating array and matrix using fuction 

In [8]:
arr = np.zeros((3,6))
a =10
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
arr = np.ones((4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr = np.eye(3,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
arr = np.diag([1,2,3,4,5]) #it takes lists
print(arr)
print("\n")
print("the diagonal is ",np.diag(arr))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


the diagonal is  [1 2 3 4 5]


### Random numbers


In [31]:
arr_rand = np.random.randint(4,23,7)
arr_rand


array([ 5, 22,  4, 16, 16, 12, 16])

In [46]:
#randint with one or two parameter will print one ranom int taking it as upper and lower limits
arr_rand =np.random.randint(5)
print(arr_rand)

2


In [56]:
#random.rand
arr = np.random.rand(4)
print(arr)
arr_1 = np.random.rand(3,4)
arr_1
#will print between 0 and 1

[0.63640052 0.82697684 0.3985957  0.41804407]


array([[0.05490411, 0.27747217, 0.93271755, 0.80713294],
       [0.6517766 , 0.9220729 , 0.58879585, 0.40541503],
       [0.56898802, 0.66564446, 0.12391907, 0.90952716]])

In [60]:
#random.randn
arr =np.random.randn(4)
print(arr)
#centered around 0, mean will be around zero
print(f"mean of {arr} is {np.mean(arr)}")

[ 0.85321675  0.29826478  0.25857668 -1.78441002]
mean of [ 0.85321675  0.29826478  0.25857668 -1.78441002] is -0.09358795379808538


In [62]:
#randomint but using matrix
arr = np.random.randint(1,100,size=(3,5))
arr

array([[64, 18, 58, 32, 13],
       [27, 29, 16, 50, 99],
       [96, 50, 83, 30, 83]])

In [47]:
#choosing using random from array
arr = np.random.choice([1,4,67,35,68], size = 4, replace= True)
arr

array([35,  4, 67, 68])

### when to randomly select but only 6 unique numbers shold fill all the places and no other number allowed

In [66]:
nums = np.random.choice(np.arange(1,25), size=6, replace=False)
np.random.choice(nums, size=(3,4), replace=True)
#note :- here replace is not mandatory to write, 2:- if Replace = false then will give error sisce choice cannot fill 12 with only 6
#can use other method wehere empty place will be replaced by 0 instead using zeroes 

array([[11, 19, 13,  8],
       [ 8, 11,  3, 13],
       [ 8, 22, 22, 13]])