#### data slicing 

In [2]:
import numpy as np

In [7]:
arr = np.array([4,54,65,38,34,85,72])
arr

array([ 4, 54, 65, 38, 34, 85, 72])

In [8]:
arr[::-1]

array([72, 85, 34, 38, 65, 54,  4])

In [9]:
arr[4:5]

array([34])

In [10]:
arr[-3:-1]

array([34, 85])

In [11]:
arr[2:-1]

array([65, 38, 34, 85])

In [12]:
arr[::3]
#entire array but every third element

array([ 4, 38, 72])

In [13]:
arr[-3:-5]
#wrong since we have to move left to right not vice versa

array([], dtype=int32)

In [14]:
arr[4:2]
#wrong

array([], dtype=int32)

In [15]:
arr[3:-5]
#wrong

array([], dtype=int32)

#### 2D slicing 

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[8,9,10]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

###### can do it using matrix[1][0] two square brackets, but will use single square bracket with comma

In [7]:
matrix[1,2]

6

In [8]:
matrix = np.random.randint(1,200,30).reshape(5,-1)
matrix

array([[198, 122,  33,  87,  79, 174],
       [128, 155,  80, 191,  22,  81],
       [120, 199, 118,  80, 196,  23],
       [ 33, 189, 151, 189, 130, 164],
       [105,  61,  60,  93, 153, 134]])

In [9]:
matrix[3:,4:]

array([[130, 164],
       [153, 134]])

In [10]:
matrix[2:4,3:5]

array([[ 80, 196],
       [189, 130]])