In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,100,20)

In [4]:
arr

array([ 6, 23, 81, 87, 62,  8, 97, 30, 56, 94, 14, 64, 63, 36, 66,  3,  5,
       73, 98, 59])

In [5]:
arr.reshape(2,10)

array([[ 6, 23, 81, 87, 62,  8, 97, 30, 56, 94],
       [14, 64, 63, 36, 66,  3,  5, 73, 98, 59]])

In [6]:
arr.reshape(5,4)

array([[ 6, 23, 81, 87],
       [62,  8, 97, 30],
       [56, 94, 14, 64],
       [63, 36, 66,  3],
       [ 5, 73, 98, 59]])

In [7]:
arr
#arr value didn't changed since we did not reassign it and just printed the operation

array([ 6, 23, 81, 87, 62,  8, 97, 30, 56, 94, 14, 64, 63, 36, 66,  3,  5,
       73, 98, 59])

In [8]:
arr = arr.reshape(2,2,5)

In [9]:
arr

array([[[ 6, 23, 81, 87, 62],
        [ 8, 97, 30, 56, 94]],

       [[14, 64, 63, 36, 66],
        [ 3,  5, 73, 98, 59]]])

In [10]:
arr = arr.reshape(20)
arr

array([ 6, 23, 81, 87, 62,  8, 97, 30, 56, 94, 14, 64, 63, 36, 66,  3,  5,
       73, 98, 59])

In [11]:
arr = arr.reshape(2,2,5)
#arr = arr.reshape(15)
#reshape(15) will not work since it arr of 20 cannot bemade 15

In [14]:
arr

array([[[ 6, 23, 81, 87, 62],
        [ 8, 97, 30, 56, 94]],

       [[14, 64, 63, 36, 66],
        [ 3,  5, 73, 98, 59]]])

### using the -1 in reshape

In [13]:
arr.reshape(-1)

array([ 6, 23, 81, 87, 62,  8, 97, 30, 56, 94, 14, 64, 63, 36, 66,  3,  5,
       73, 98, 59])

In [15]:
arr.reshape(-1,5)

array([[ 6, 23, 81, 87, 62],
       [ 8, 97, 30, 56, 94],
       [14, 64, 63, 36, 66],
       [ 3,  5, 73, 98, 59]])

In [16]:
arr.reshape(2,-1)

array([[ 6, 23, 81, 87, 62,  8, 97, 30, 56, 94],
       [14, 64, 63, 36, 66,  3,  5, 73, 98, 59]])