### shuffle and unique 

In [1]:
import numpy as np

In [2]:
np.random.seed(100)

In [5]:
arr = np.random.randint(1,15,15)
arr

array([ 9,  5, 12, 13, 11,  1, 12, 10, 14,  7,  3, 12, 13,  5,  2])

In [9]:
np.random.shuffle(arr)
arr

array([ 5, 14,  1, 12, 13,  7, 11,  5,  3, 12, 10,  2, 12,  9, 13])

In [10]:
np.unique(arr)

array([ 1,  2,  3,  5,  7,  9, 10, 11, 12, 13, 14])

In [11]:
np.unique(arr).size

11

In [13]:
np.unique(arr, return_index=True,return_counts=True)
#returns index of unique numbers and count of times they occured

(array([ 1,  2,  3,  5,  7,  9, 10, 11, 12, 13, 14]),
 array([ 2, 11,  8,  0,  5, 13, 10,  6,  3,  4,  1], dtype=int64),
 array([1, 1, 1, 2, 1, 1, 1, 1, 3, 2, 1], dtype=int64))