### scaler in numpy (scaler means normal number )

In [1]:
import numpy as np

In [4]:
arr = np.array([1,4,6,234,78,43])

In [5]:
arr *2

array([  2,   8,  12, 468, 156,  86])

In [6]:
arr ** 2


array([    1,    16,    36, 54756,  6084,  1849])

In [7]:
arr / 3

array([ 0.33333333,  1.33333333,  2.        , 78.        , 26.        ,
       14.33333333])

In [8]:
arr + 34

array([ 35,  38,  40, 268, 112,  77])

In [9]:
arr -3

array([ -2,   1,   3, 231,  75,  40])

In [10]:
#works for 2d and 3d as well in the same fashion 

In [11]:
arr = arr.reshape(2,-1)

In [12]:
arr**2

array([[    1,    16,    36],
       [54756,  6084,  1849]])

In [13]:
arr + 69

array([[ 70,  73,  75],
       [303, 147, 112]])