### axis 0 and 1 for column and row

In [1]:
import numpy as np

In [6]:
arr = np.random.randint(4,18,9).reshape(3,3)
arr

array([[14,  7,  9],
       [17,  9, 17],
       [ 4,  6,  8]])

In [7]:
arr.sum()


91

In [8]:
np.sum(arr)
#two ways can be done

91

In [9]:
np.min(arr,axis=1)

array([7, 9, 4])

In [10]:
np.argmin(arr, axis=0)

array([2, 2, 2], dtype=int64)

In [11]:
np.sum(arr,axis=1)

array([30, 43, 18])

#### cummulative sum 

In [12]:
np.cumsum(arr)

array([14, 21, 30, 47, 56, 73, 77, 83, 91])

In [13]:
np.cumsum(arr, axis=0)

array([[14,  7,  9],
       [31, 16, 26],
       [35, 22, 34]])

In [14]:
np.cumsum(arr,axis=1)

array([[14, 21, 30],
       [17, 26, 43],
       [ 4, 10, 18]])